# Generated by Django 2.1.7 on 2019-03-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazyPetsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_x', models.FloatField()),
                ('mouse_y', models.FloatField()),
                ('eye_right_x', models.FloatField()),
                ('eye_right_y', models.FloatField()),
                ('eye_left_x', models.FloatField()),
                ('eye_left_y', models.FloatField()),
                ('nose_x', models.FloatField()),
                ('nose_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_x', models.FloatField()),
                ('mouse_y', models.FloatField()),
                ('eye_right_x', models.FloatField()),
                ('eye_right_y', models.FloatField()),
                ('eye_left_x', models.FloatField()),
                ('eye_left_y', models.FloatField()),
                ('nose_x', models.FloatField()),
                ('nose_y', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
