# Generated by Django 2.1.7 on 2019-03-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crazyPetsApp', '0002_auto_20190320_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='mouse_x',
            new_name='mouth_x',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='mouse_y',
            new_name='mouth_y',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='mouse_x',
            new_name='mouth_x',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='mouse_y',
            new_name='mouth_y',
        ),
    ]
